name: CI
on: pull_request
jobs:
  linux:
    name: x86_64-linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Fetch LLVM
        id: fetch-llvm
        uses: birth-software/fetch-llvm@fix
        with:
          version: '17.0.6'
          cpu: 'x86_64_v3'
      - name: Test it exists
        env:
          MY_LLVM_PATH: ${{ steps.fetch-llvm.outputs.MY_LLVM_PATH }}
        run: ls $GITHUBMY_LLVM_PATH/bin
  windows:
    name: x86_64-windows
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Fetch LLVM
        id: fetch-llvm
        uses: birth-software/fetch-llvm@first
        with:
          version: '17.0.6'
          cpu: 'x86_64_v3'
      - name: Test it exists
        env:
          MY_LLVM_PATH: ${{ steps.fetch-llvm.outputs.MY_LLVM_PATH }}
        run: ls $GITHUBMY_LLVM_PATH/bin
  macos:
    name: aarch64-macos
    runs-on: flyci-macos-large-latest-m1
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Fetch LLVM
        id: fetch-llvm
        uses: birth-software/fetch-llvm@first
        with:
          version: '17.0.6'
          cpu: 'apple_m1'
      - name: Test it exists
        env:
          MY_LLVM_PATH: ${{ steps.fetch-llvm.outputs.MY_LLVM_PATH }}
        run: ls $GITHUBMY_LLVM_PATH/bin
